name: 'Setup frontend dependencies'
description: 'Setup pnpm, Node.js, and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
