services:
  # Config.jsonをマウントしたり等、現時点でcontrollerから開始できないホストを立ち上げたい時のサンプル
  # ポイントはgRPCをサーブするポートをlabelで宣言すること。labelがないとcontrollerに認識されない
  headless:
    image: ghcr.io/hantabaru1014/baru-reso-headless-container:latest
    labels:
      - dev.baru.brhdl.rpc-port=5001
    environment:
      - RpcHostUrl=http://localhost:5001
      - HeadlessUserCredential=<YOUR_HEADLESS_USER_CREDENTIAL>
      - HeadlessUserPassword=<YOUR_HEADLESS_USER_PASSWORD>
    volumes:
      - ./Config.json:/app/Config/Config.json
    network_mode: host
