// Code generated by MockGen. DO NOT EDIT.
// Source: lib/skyfrost/client.go
//
// Generated by this command:
//
//	mockgen -source=lib/skyfrost/client.go -destination=lib/skyfrost/mock/mock_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	skyfrost "github.com/hantabaru1014/baru-reso-headless-controller/lib/skyfrost"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchUserInfo mocks base method.
func (m *MockClient) FetchUserInfo(ctx context.Context, resoniteID string) (*skyfrost.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUserInfo", ctx, resoniteID)
	ret0, _ := ret[0].(*skyfrost.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUserInfo indicates an expected call of FetchUserInfo.
func (mr *MockClientMockRecorder) FetchUserInfo(ctx, resoniteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUserInfo", reflect.TypeOf((*MockClient)(nil).FetchUserInfo), ctx, resoniteID)
}

// GetContacts mocks base method.
func (m *MockClient) GetContacts(ctx context.Context, credential, password string) ([]skyfrost.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContacts", ctx, credential, password)
	ret0, _ := ret[0].([]skyfrost.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContacts indicates an expected call of GetContacts.
func (mr *MockClientMockRecorder) GetContacts(ctx, credential, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContacts", reflect.TypeOf((*MockClient)(nil).GetContacts), ctx, credential, password)
}

// GetStorageInfo mocks base method.
func (m *MockClient) GetStorageInfo(ctx context.Context, credential, password, ownerId string) (*skyfrost.StorageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageInfo", ctx, credential, password, ownerId)
	ret0, _ := ret[0].(*skyfrost.StorageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageInfo indicates an expected call of GetStorageInfo.
func (mr *MockClientMockRecorder) GetStorageInfo(ctx, credential, password, ownerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageInfo", reflect.TypeOf((*MockClient)(nil).GetStorageInfo), ctx, credential, password, ownerId)
}

// UserLogin mocks base method.
func (m *MockClient) UserLogin(ctx context.Context, credential, password string) (*skyfrost.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogin", ctx, credential, password)
	ret0, _ := ret[0].(*skyfrost.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLogin indicates an expected call of UserLogin.
func (mr *MockClientMockRecorder) UserLogin(ctx, credential, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*MockClient)(nil).UserLogin), ctx, credential, password)
}
