// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file hdlctrl/v1/user.proto (package hdlctrl.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hdlctrl/v1/user.proto.
 */
export const file_hdlctrl_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChVoZGxjdHJsL3YxL3VzZXIucHJvdG8SCmhkbGN0cmwudjEiOAoQVG9rZW5TZXRSZXNwb25zZRINCgV0b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJIjkKGUdldFRva2VuQnlQYXNzd29yZFJlcXVlc3QSCgoCaWQYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiFQoTUmVmcmVzaFRva2VuUmVxdWVzdDK7AQoLVXNlclNlcnZpY2USWwoSR2V0VG9rZW5CeVBhc3N3b3JkEiUuaGRsY3RybC52MS5HZXRUb2tlbkJ5UGFzc3dvcmRSZXF1ZXN0GhwuaGRsY3RybC52MS5Ub2tlblNldFJlc3BvbnNlIgASTwoMUmVmcmVzaFRva2VuEh8uaGRsY3RybC52MS5SZWZyZXNoVG9rZW5SZXF1ZXN0GhwuaGRsY3RybC52MS5Ub2tlblNldFJlc3BvbnNlIgBCtwEKDmNvbS5oZGxjdHJsLnYxQglVc2VyUHJvdG9QAVpRZ2l0aHViLmNvbS9oYW50YWJhcnUxMDE0L2JhcnUtcmVzby1oZWFkbGVzcy1jb250cm9sbGVyL3BiZ2VuL2hkbGN0cmwvdjE7aGRsY3RybHYxogIDSFhYqgIKSGRsY3RybC5WMcoCCkhkbGN0cmxcVjHiAhZIZGxjdHJsXFYxXEdQQk1ldGFkYXRh6gILSGRsY3RybDo6VjFiBnByb3RvMw");

/**
 * @generated from message hdlctrl.v1.TokenSetResponse
 */
export type TokenSetResponse = Message<"hdlctrl.v1.TokenSetResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;
};

/**
 * Describes the message hdlctrl.v1.TokenSetResponse.
 * Use `create(TokenSetResponseSchema)` to create a new message.
 */
export const TokenSetResponseSchema: GenMessage<TokenSetResponse> = /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 0);

/**
 * @generated from message hdlctrl.v1.GetTokenByPasswordRequest
 */
export type GetTokenByPasswordRequest = Message<"hdlctrl.v1.GetTokenByPasswordRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message hdlctrl.v1.GetTokenByPasswordRequest.
 * Use `create(GetTokenByPasswordRequestSchema)` to create a new message.
 */
export const GetTokenByPasswordRequestSchema: GenMessage<GetTokenByPasswordRequest> = /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 1);

/**
 * 既に持っているトークンをheaderに付与してリクエストする
 *
 * @generated from message hdlctrl.v1.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"hdlctrl.v1.RefreshTokenRequest"> & {
};

/**
 * Describes the message hdlctrl.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 2);

/**
 * @generated from message hdlctrl.v1.ValidateRegistrationTokenRequest
 */
export type ValidateRegistrationTokenRequest = Message<"hdlctrl.v1.ValidateRegistrationTokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message hdlctrl.v1.ValidateRegistrationTokenRequest.
 * Use `create(ValidateRegistrationTokenRequestSchema)` to create a new message.
 */
export const ValidateRegistrationTokenRequestSchema: GenMessage<ValidateRegistrationTokenRequest> = /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 3);

/**
 * @generated from message hdlctrl.v1.ValidateRegistrationTokenResponse
 */
export type ValidateRegistrationTokenResponse = Message<"hdlctrl.v1.ValidateRegistrationTokenResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;

  /**
   * @generated from field: string resonite_id = 2;
   */
  resoniteId: string;
};

/**
 * Describes the message hdlctrl.v1.ValidateRegistrationTokenResponse.
 * Use `create(ValidateRegistrationTokenResponseSchema)` to create a new message.
 */
export const ValidateRegistrationTokenResponseSchema: GenMessage<ValidateRegistrationTokenResponse> = /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 4);

/**
 * @generated from message hdlctrl.v1.RegisterWithTokenRequest
 */
export type RegisterWithTokenRequest = Message<"hdlctrl.v1.RegisterWithTokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message hdlctrl.v1.RegisterWithTokenRequest.
 * Use `create(RegisterWithTokenRequestSchema)` to create a new message.
 */
export const RegisterWithTokenRequestSchema: GenMessage<RegisterWithTokenRequest> = /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 5);

/**
 * @generated from service hdlctrl.v1.UserService
 */
export const UserService: GenService<{
  /**
   * 認証なしRPC
   *
   * @generated from rpc hdlctrl.v1.UserService.GetTokenByPassword
   */
  getTokenByPassword: {
    methodKind: "unary";
    input: typeof GetTokenByPasswordRequestSchema;
    output: typeof TokenSetResponseSchema;
  },
  /**
   * @generated from rpc hdlctrl.v1.UserService.ValidateRegistrationToken
   */
  validateRegistrationToken: {
    methodKind: "unary";
    input: typeof ValidateRegistrationTokenRequestSchema;
    output: typeof ValidateRegistrationTokenResponseSchema;
  },
  /**
   * @generated from rpc hdlctrl.v1.UserService.RegisterWithToken
   */
  registerWithToken: {
    methodKind: "unary";
    input: typeof RegisterWithTokenRequestSchema;
    output: typeof TokenSetResponseSchema;
  },
  /**
   * 認証付きRPC
   *
   * @generated from rpc hdlctrl.v1.UserService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof TokenSetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_hdlctrl_v1_user, 0);

