// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/hantabaru1014/baru-reso-headless-controller/adapter"
	"github.com/hantabaru1014/baru-reso-headless-controller/adapter/hostconnector"
	"github.com/hantabaru1014/baru-reso-headless-controller/adapter/resonitelink"
	"github.com/hantabaru1014/baru-reso-headless-controller/adapter/rpc"
	"github.com/hantabaru1014/baru-reso-headless-controller/adapter/sessionstate"
	"github.com/hantabaru1014/baru-reso-headless-controller/config"
	"github.com/hantabaru1014/baru-reso-headless-controller/db"
	"github.com/hantabaru1014/baru-reso-headless-controller/lib/blobstore"
	"github.com/hantabaru1014/baru-reso-headless-controller/lib/skyfrost"
	"github.com/hantabaru1014/baru-reso-headless-controller/usecase"
	"github.com/hantabaru1014/baru-reso-headless-controller/usecase/port"
	"github.com/hantabaru1014/baru-reso-headless-controller/worker"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.EnvConfig) (*Server, error) {
	databaseConfig := ProvideDatabaseConfig(cfg)
	queries := db.NewQueries(databaseConfig)
	defaultClient := skyfrost.NewDefaultClient()
	userUsecase := usecase.NewUserUsecase(queries, defaultClient)
	userService := rpc.NewUserService(userUsecase)
	dockerConfig := ProvideDockerConfig(cfg)
	grpcConfig := ProvideGRPCConfig(cfg)
	dockerHostConnector := hostconnector.NewDockerHostConnector(dockerConfig, grpcConfig)
	headlessHostRepository := adapter.NewHeadlessHostRepository(queries, dockerHostConnector, grpcConfig)
	sessionRepository := adapter.NewSessionRepository(queries)
	headlessAccountUsecase := usecase.NewHeadlessAccountUsecase(queries, defaultClient)
	headlessAccountFetcher := ProvideHeadlessAccountFetcher(headlessAccountUsecase)
	workerConfig := ProvideWorkerConfig(cfg)
	hostUpgradeOrchestrator := worker.NewHostUpgradeOrchestrator(headlessHostRepository, sessionRepository, headlessAccountFetcher, workerConfig)
	memoryCache := sessionstate.NewMemoryCache()
	serverConfig := ProvideServerConfig(cfg)
	resoniteLinkConfig := ProvideResoniteLinkConfig(cfg)
	sessionUsecase := usecase.NewSessionUsecase(sessionRepository, headlessHostRepository, hostUpgradeOrchestrator, memoryCache, serverConfig, resoniteLinkConfig)
	headlessHostUsecase := usecase.NewHeadlessHostUsecase(headlessHostRepository, sessionRepository, sessionUsecase, headlessAccountUsecase)
	rustFSConfig := ProvideRustFSConfig(cfg)
	minioClient, err := blobstore.NewMinioClient(rustFSConfig)
	if err != nil {
		return nil, err
	}
	blobUsecase := usecase.NewBlobUsecase(sessionRepository, headlessHostRepository, minioClient)
	scheduledSessionOperationRepository := adapter.NewScheduledSessionOperationRepository(queries)
	scheduledSessionOperationUsecase := usecase.NewScheduledSessionOperationUsecase(scheduledSessionOperationRepository)
	controllerService := rpc.NewControllerService(headlessHostRepository, sessionRepository, headlessHostUsecase, headlessAccountUsecase, sessionUsecase, blobUsecase, scheduledSessionOperationUsecase, defaultClient)
	imageChecker := worker.NewImageChecker(dockerHostConnector, workerConfig)
	dockerEventWatcher := worker.NewDockerEventWatcher(dockerHostConnector, queries, workerConfig)
	sqlHostEventStore := worker.NewSQLHostEventStore(queries)
	sessionStateSyncHandler := worker.NewSessionStateSyncHandler(sessionRepository, headlessHostRepository, memoryCache)
	sessionLifecycleHandler := worker.NewSessionLifecycleHandler(sessionRepository)
	loggingHostEventHandler := worker.NewLoggingHostEventHandler()
	v := ProvideHostEventHandlers(sessionStateSyncHandler, sessionLifecycleHandler, hostUpgradeOrchestrator, loggingHostEventHandler)
	hostEventWatcher := worker.NewHostEventWatcher(headlessHostRepository, sqlHostEventStore, workerConfig, v)
	scheduledOperationExecutor := ProvideScheduledOperationExecutor(scheduledSessionOperationRepository, sessionUsecase, sessionRepository, memoryCache)
	manager := ProvideWorkerManager(imageChecker, dockerEventWatcher, hostEventWatcher, hostUpgradeOrchestrator, scheduledOperationExecutor, sessionUsecase)
	bridge := resonitelink.NewBridge(headlessHostRepository, sessionRepository, resoniteLinkConfig)
	server := NewServer(userService, controllerService, manager, minioClient, bridge)
	return server, nil
}

func InitializeCli(cfg *config.EnvConfig) *Cli {
	databaseConfig := ProvideDatabaseConfig(cfg)
	queries := db.NewQueries(databaseConfig)
	defaultClient := skyfrost.NewDefaultClient()
	userUsecase := usecase.NewUserUsecase(queries, defaultClient)
	dockerConfig := ProvideDockerConfig(cfg)
	grpcConfig := ProvideGRPCConfig(cfg)
	dockerHostConnector := hostconnector.NewDockerHostConnector(dockerConfig, grpcConfig)
	headlessHostRepository := adapter.NewHeadlessHostRepository(queries, dockerHostConnector, grpcConfig)
	sessionRepository := adapter.NewSessionRepository(queries)
	noopHostDrainer := port.NoopHostDrainer{}
	memoryCache := sessionstate.NewMemoryCache()
	serverConfig := ProvideServerConfig(cfg)
	resoniteLinkConfig := ProvideResoniteLinkConfig(cfg)
	sessionUsecase := usecase.NewSessionUsecase(sessionRepository, headlessHostRepository, noopHostDrainer, memoryCache, serverConfig, resoniteLinkConfig)
	headlessAccountUsecase := usecase.NewHeadlessAccountUsecase(queries, defaultClient)
	headlessHostUsecase := usecase.NewHeadlessHostUsecase(headlessHostRepository, sessionRepository, sessionUsecase, headlessAccountUsecase)
	scheduledSessionOperationRepository := adapter.NewScheduledSessionOperationRepository(queries)
	scheduledSessionOperationUsecase := usecase.NewScheduledSessionOperationUsecase(scheduledSessionOperationRepository)
	cli := NewCli(queries, userUsecase, headlessHostUsecase, scheduledSessionOperationUsecase, defaultClient)
	return cli
}

// wire.go:

// Config providers
func ProvideDatabaseConfig(cfg *config.EnvConfig) *config.DatabaseConfig {
	return &cfg.Database
}

func ProvideDockerConfig(cfg *config.EnvConfig) *config.DockerConfig {
	return &cfg.Docker
}

func ProvideGRPCConfig(cfg *config.EnvConfig) *config.GRPCConfig {
	return &cfg.GRPC
}

func ProvideWorkerConfig(cfg *config.EnvConfig) *config.WorkerConfig {
	return &cfg.Worker
}

func ProvideServerConfig(cfg *config.EnvConfig) *config.ServerConfig {
	return &cfg.Server
}

func ProvideRustFSConfig(cfg *config.EnvConfig) *config.RustFSConfig {
	return &cfg.RustFS
}

func ProvideResoniteLinkConfig(cfg *config.EnvConfig) *config.ResoniteLinkConfig {
	return &cfg.ResoniteLink
}

// ProvideWorkerManager groups the concrete background workers AND
// performs two post-construction links that wire itself cannot express:
//   - The orchestrator needs a SessionStopper (SessionUsecase), but
//     SessionUsecase needs a HostDrainer (the orchestrator). Wire can
//     pick only one direction at construction time; we close the cycle
//     by setting the stopper here, after both ends exist.
//   - The orchestrator subscribes to ImageChecker so registry polling
//     happens in exactly one place.
func ProvideWorkerManager(
	imageChecker *worker.ImageChecker,
	dockerEventWatcher *worker.DockerEventWatcher,
	hostEventWatcher *worker.HostEventWatcher,
	upgradeOrchestrator *worker.HostUpgradeOrchestrator,
	scheduledOpExecutor *worker.ScheduledOperationExecutor,
	sessionStopper port.SessionStopper,
) *worker.Manager {
	upgradeOrchestrator.SetSessionStopper(sessionStopper)
	imageChecker.Subscribe(upgradeOrchestrator.OnNewImage)

	return worker.NewManager([]worker.Runner{
		imageChecker,
		dockerEventWatcher,
		hostEventWatcher,
		upgradeOrchestrator,
		scheduledOpExecutor,
	})
}

// ProvideScheduledOperationExecutor は scheduled session operation worker を
// 構築する. SessionUsecase をそのまま SessionOperator として渡し、interface
// 経由で worker パッケージから usecase パッケージへの依存を切る.
func ProvideScheduledOperationExecutor(
	repo port.ScheduledSessionOperationRepository,
	suc *usecase.SessionUsecase,
	srepo port.SessionRepository,
	stateCache port.SessionStateCache,
) *worker.ScheduledOperationExecutor {
	return worker.NewScheduledOperationExecutor(repo, suc, srepo, stateCache, worker.ScheduledOperationExecutorOptions{})
}

// ProvideHostEventHandlers gathers consumers for the per-host event
// streams. Order matters: the logging handler runs last so other handlers'
// DB writes are visible by the time we log the event.
func ProvideHostEventHandlers(
	sessionStateSyncHandler *worker.SessionStateSyncHandler,
	sessionLifecycleHandler *worker.SessionLifecycleHandler,
	upgradeOrchestrator *worker.HostUpgradeOrchestrator,
	loggingHandler *worker.LoggingHostEventHandler,
) []worker.HostEventHandler {
	return []worker.HostEventHandler{sessionStateSyncHandler, sessionLifecycleHandler, upgradeOrchestrator, loggingHandler}
}

// ProvideHeadlessAccountFetcher exposes HeadlessAccountUsecase under the
// orchestrator's narrow interface so the worker package does not have to
// depend on the entire usecase package.
func ProvideHeadlessAccountFetcher(u *usecase.HeadlessAccountUsecase) worker.HeadlessAccountFetcher {
	return u
}

var ConfigSet = wire.NewSet(
	ProvideDatabaseConfig,
	ProvideDockerConfig,
	ProvideGRPCConfig,
	ProvideWorkerConfig,
	ProvideServerConfig,
	ProvideRustFSConfig,
	ProvideResoniteLinkConfig,
)
