// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: container_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContainerLogsByHostID = `-- name: DeleteContainerLogsByHostID :exec
DELETE FROM container_logs
WHERE tag LIKE 'headless-' || $1 || '-%'
`

// 特定のホストIDに関連するすべてのログを削除
// タグは "headless-{hostID}-{instanceID}" の形式
func (q *Queries) DeleteContainerLogsByHostID(ctx context.Context, hostID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteContainerLogsByHostID, hostID)
	return err
}

const getContainerLogsAfter = `-- name: GetContainerLogsAfter :many
SELECT tag, ts, data, id
FROM container_logs
WHERE tag = $1
  AND id > $2::bigint
ORDER BY id ASC
LIMIT $3
`

type GetContainerLogsAfterParams struct {
	Tag     pgtype.Text
	AfterID int64
	MaxRows int32
}

// 特定のタグ（hostID + instanceID）のログを、after_id より大きい ID の中から古い順に取得
// (新しい方向へのページネーション)
func (q *Queries) GetContainerLogsAfter(ctx context.Context, arg GetContainerLogsAfterParams) ([]ContainerLog, error) {
	rows, err := q.db.Query(ctx, getContainerLogsAfter, arg.Tag, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContainerLog
	for rows.Next() {
		var i ContainerLog
		if err := rows.Scan(
			&i.Tag,
			&i.Ts,
			&i.Data,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainerLogsBefore = `-- name: GetContainerLogsBefore :many
SELECT tag, ts, data, id
FROM container_logs
WHERE tag = $1
  AND id < $2::bigint
ORDER BY id DESC
LIMIT $3
`

type GetContainerLogsBeforeParams struct {
	Tag      pgtype.Text
	BeforeID int64
	MaxRows  int32
}

// 特定のタグ（hostID + instanceID）のログを、before_id より小さい ID の中から新しい順に取得
// (古い方向へのページネーション / 最新からの初回取得)
// カーソルなしで最新から取得する場合は before_id に bigint の最大値を渡す
func (q *Queries) GetContainerLogsBefore(ctx context.Context, arg GetContainerLogsBeforeParams) ([]ContainerLog, error) {
	rows, err := q.db.Query(ctx, getContainerLogsBefore, arg.Tag, arg.BeforeID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContainerLog
	for rows.Next() {
		var i ContainerLog
		if err := rows.Scan(
			&i.Tag,
			&i.Ts,
			&i.Data,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstanceTimestamps = `-- name: GetInstanceTimestamps :many
SELECT
    CAST(SUBSTRING(tag FROM 'headless-[^-]+-(\d+)') AS INTEGER) AS instance_id,
    MIN(ts) AS first_log_at,
    MAX(ts) AS last_log_at,
    COUNT(*) AS log_count
FROM container_logs
WHERE tag LIKE 'headless-' || $1 || '-%'
GROUP BY SUBSTRING(tag FROM 'headless-[^-]+-(\d+)')
ORDER BY instance_id DESC
`

type GetInstanceTimestampsRow struct {
	InstanceID int32
	FirstLogAt interface{}
	LastLogAt  interface{}
	LogCount   int64
}

// 各インスタンスのログの最初と最後のタイムスタンプを取得
func (q *Queries) GetInstanceTimestamps(ctx context.Context, hostID pgtype.Text) ([]GetInstanceTimestampsRow, error) {
	rows, err := q.db.Query(ctx, getInstanceTimestamps, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstanceTimestampsRow
	for rows.Next() {
		var i GetInstanceTimestampsRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.FirstLogAt,
			&i.LastLogAt,
			&i.LogCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContainerLog = `-- name: InsertContainerLog :exec
INSERT INTO container_logs (tag, ts, data) VALUES ($1, $2, $3)
`

type InsertContainerLogParams struct {
	Tag  pgtype.Text
	Ts   pgtype.Timestamp
	Data []byte
}

// テスト用
func (q *Queries) InsertContainerLog(ctx context.Context, arg InsertContainerLogParams) error {
	_, err := q.db.Exec(ctx, insertContainerLog, arg.Tag, arg.Ts, arg.Data)
	return err
}

const searchContainerLogAfter = `-- name: SearchContainerLogAfter :one
SELECT id
FROM container_logs
WHERE tag = $1
  AND id > $2::bigint
  AND data->>'log' ILIKE $3::text
ORDER BY id ASC
LIMIT 1
`

type SearchContainerLogAfterParams struct {
	Tag     pgtype.Text
	AfterID int64
	Pattern string
}

// after_id より大きい ID の中から、本文がパターンに一致する最も古いログの ID を返す
func (q *Queries) SearchContainerLogAfter(ctx context.Context, arg SearchContainerLogAfterParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, searchContainerLogAfter, arg.Tag, arg.AfterID, arg.Pattern)
	var id pgtype.Int8
	err := row.Scan(&id)
	return id, err
}

const searchContainerLogBefore = `-- name: SearchContainerLogBefore :one
SELECT id
FROM container_logs
WHERE tag = $1
  AND id < $2::bigint
  AND data->>'log' ILIKE $3::text
ORDER BY id DESC
LIMIT 1
`

type SearchContainerLogBeforeParams struct {
	Tag      pgtype.Text
	BeforeID int64
	Pattern  string
}

// before_id より小さい ID の中から、本文がパターンに一致する最も新しいログの ID を返す
// カーソルなしで最新から検索する場合は before_id に bigint の最大値を渡す
func (q *Queries) SearchContainerLogBefore(ctx context.Context, arg SearchContainerLogBeforeParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, searchContainerLogBefore, arg.Tag, arg.BeforeID, arg.Pattern)
	var id pgtype.Int8
	err := row.Scan(&id)
	return id, err
}
