// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationToken = `-- name: CreateRegistrationToken :exec
INSERT INTO registration_tokens (token, resonite_id, expires_at) VALUES ($1, $2, $3)
`

type CreateRegistrationTokenParams struct {
	Token      string
	ResoniteID string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) error {
	_, err := q.db.Exec(ctx, createRegistrationToken,
		arg.Token,
		arg.ResoniteID,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRegistrationTokens = `-- name: DeleteExpiredRegistrationTokens :exec
DELETE FROM registration_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRegistrationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRegistrationTokens)
	return err
}

const getRegistrationToken = `-- name: GetRegistrationToken :one
SELECT token, resonite_id, expires_at, used_at, created_at FROM registration_tokens WHERE token = $1
`

func (q *Queries) GetRegistrationToken(ctx context.Context, token string) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, getRegistrationToken, token)
	var i RegistrationToken
	err := row.Scan(
		&i.Token,
		&i.ResoniteID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidRegistrationToken = `-- name: GetValidRegistrationToken :one
SELECT token, resonite_id, expires_at, used_at, created_at FROM registration_tokens
WHERE token = $1
  AND expires_at > NOW()
  AND used_at IS NULL
`

func (q *Queries) GetValidRegistrationToken(ctx context.Context, token string) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, getValidRegistrationToken, token)
	var i RegistrationToken
	err := row.Scan(
		&i.Token,
		&i.ResoniteID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markRegistrationTokenUsed = `-- name: MarkRegistrationTokenUsed :exec
UPDATE registration_tokens SET used_at = NOW() WHERE token = $1
`

func (q *Queries) MarkRegistrationTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markRegistrationTokenUsed, token)
	return err
}
