// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resonite_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestBuiltResoniteVersionByBranch = `-- name: GetLatestBuiltResoniteVersionByBranch :one
SELECT manifest_id, branch, game_version, released_at, build_status, image_tag, built_with_app_version, built_at, build_error, created_at, updated_at FROM resonite_versions
WHERE branch = $1
  AND build_status = 'built'
  AND game_version IS NOT NULL
ORDER BY released_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBuiltResoniteVersionByBranch(ctx context.Context, branch string) (ResoniteVersion, error) {
	row := q.db.QueryRow(ctx, getLatestBuiltResoniteVersionByBranch, branch)
	var i ResoniteVersion
	err := row.Scan(
		&i.ManifestID,
		&i.Branch,
		&i.GameVersion,
		&i.ReleasedAt,
		&i.BuildStatus,
		&i.ImageTag,
		&i.BuiltWithAppVersion,
		&i.BuiltAt,
		&i.BuildError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResoniteVersion = `-- name: GetResoniteVersion :one
SELECT manifest_id, branch, game_version, released_at, build_status, image_tag, built_with_app_version, built_at, build_error, created_at, updated_at FROM resonite_versions
WHERE manifest_id = $1 AND branch = $2 LIMIT 1
`

type GetResoniteVersionParams struct {
	ManifestID string
	Branch     string
}

func (q *Queries) GetResoniteVersion(ctx context.Context, arg GetResoniteVersionParams) (ResoniteVersion, error) {
	row := q.db.QueryRow(ctx, getResoniteVersion, arg.ManifestID, arg.Branch)
	var i ResoniteVersion
	err := row.Scan(
		&i.ManifestID,
		&i.Branch,
		&i.GameVersion,
		&i.ReleasedAt,
		&i.BuildStatus,
		&i.ImageTag,
		&i.BuiltWithAppVersion,
		&i.BuiltAt,
		&i.BuildError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResoniteVersionByImageTag = `-- name: GetResoniteVersionByImageTag :one
SELECT manifest_id, branch, game_version, released_at, build_status, image_tag, built_with_app_version, built_at, build_error, created_at, updated_at FROM resonite_versions
WHERE image_tag = $1 LIMIT 1
`

func (q *Queries) GetResoniteVersionByImageTag(ctx context.Context, imageTag pgtype.Text) (ResoniteVersion, error) {
	row := q.db.QueryRow(ctx, getResoniteVersionByImageTag, imageTag)
	var i ResoniteVersion
	err := row.Scan(
		&i.ManifestID,
		&i.Branch,
		&i.GameVersion,
		&i.ReleasedAt,
		&i.BuildStatus,
		&i.ImageTag,
		&i.BuiltWithAppVersion,
		&i.BuiltAt,
		&i.BuildError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResoniteVersions = `-- name: ListResoniteVersions :many
SELECT manifest_id, branch, game_version, released_at, build_status, image_tag, built_with_app_version, built_at, build_error, created_at, updated_at FROM resonite_versions
WHERE ($1::text IS NULL OR branch = $1::text)
ORDER BY released_at DESC
`

func (q *Queries) ListResoniteVersions(ctx context.Context, branch pgtype.Text) ([]ResoniteVersion, error) {
	rows, err := q.db.Query(ctx, listResoniteVersions, branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResoniteVersion
	for rows.Next() {
		var i ResoniteVersion
		if err := rows.Scan(
			&i.ManifestID,
			&i.Branch,
			&i.GameVersion,
			&i.ReleasedAt,
			&i.BuildStatus,
			&i.ImageTag,
			&i.BuiltWithAppVersion,
			&i.BuiltAt,
			&i.BuildError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleBuiltResoniteVersions = `-- name: ListStaleBuiltResoniteVersions :many
SELECT manifest_id, branch, game_version, released_at, build_status, image_tag, built_with_app_version, built_at, build_error, created_at, updated_at FROM resonite_versions
WHERE build_status = 'built'
  AND branch = ANY ($1::text[])
  AND (built_with_app_version IS NULL OR built_with_app_version <> $2::text)
ORDER BY released_at DESC
`

type ListStaleBuiltResoniteVersionsParams struct {
	Branches          []string
	CurrentAppVersion string
}

// built 済みだが container repo の AppVersion と食い違う (再ビルド対象) 行.
// 対象ブランチは呼び出し側で絞る (`ANY (@branches)` で渡す).
func (q *Queries) ListStaleBuiltResoniteVersions(ctx context.Context, arg ListStaleBuiltResoniteVersionsParams) ([]ResoniteVersion, error) {
	rows, err := q.db.Query(ctx, listStaleBuiltResoniteVersions, arg.Branches, arg.CurrentAppVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResoniteVersion
	for rows.Next() {
		var i ResoniteVersion
		if err := rows.Scan(
			&i.ManifestID,
			&i.Branch,
			&i.GameVersion,
			&i.ReleasedAt,
			&i.BuildStatus,
			&i.ImageTag,
			&i.BuiltWithAppVersion,
			&i.BuiltAt,
			&i.BuildError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResoniteVersionBuilding = `-- name: SetResoniteVersionBuilding :execrows
UPDATE resonite_versions
SET build_status = 'building',
    build_error = NULL
WHERE manifest_id = $1 AND branch = $2
`

type SetResoniteVersionBuildingParams struct {
	ManifestID string
	Branch     string
}

func (q *Queries) SetResoniteVersionBuilding(ctx context.Context, arg SetResoniteVersionBuildingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setResoniteVersionBuilding, arg.ManifestID, arg.Branch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setResoniteVersionBuilt = `-- name: SetResoniteVersionBuilt :execrows
UPDATE resonite_versions
SET build_status = 'built',
    image_tag = $3::text,
    built_with_app_version = $4::text,
    built_at = NOW(),
    build_error = NULL
WHERE manifest_id = $1 AND branch = $2
`

type SetResoniteVersionBuiltParams struct {
	ManifestID          string
	Branch              string
	ImageTag            string
	BuiltWithAppVersion string
}

func (q *Queries) SetResoniteVersionBuilt(ctx context.Context, arg SetResoniteVersionBuiltParams) (int64, error) {
	result, err := q.db.Exec(ctx, setResoniteVersionBuilt,
		arg.ManifestID,
		arg.Branch,
		arg.ImageTag,
		arg.BuiltWithAppVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setResoniteVersionFailed = `-- name: SetResoniteVersionFailed :execrows
UPDATE resonite_versions
SET build_status = 'failed',
    build_error = $3::text
WHERE manifest_id = $1 AND branch = $2
`

type SetResoniteVersionFailedParams struct {
	ManifestID string
	Branch     string
	BuildError string
}

func (q *Queries) SetResoniteVersionFailed(ctx context.Context, arg SetResoniteVersionFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setResoniteVersionFailed, arg.ManifestID, arg.Branch, arg.BuildError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertResoniteVersion = `-- name: UpsertResoniteVersion :one
INSERT INTO resonite_versions (
    manifest_id, branch, game_version, released_at
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (manifest_id, branch) DO UPDATE
SET game_version = EXCLUDED.game_version,
    released_at = EXCLUDED.released_at
RETURNING manifest_id, branch, game_version, released_at, build_status, image_tag, built_with_app_version, built_at, build_error, created_at, updated_at
`

type UpsertResoniteVersionParams struct {
	ManifestID  string
	Branch      string
	GameVersion pgtype.Text
	ReleasedAt  pgtype.Timestamptz
}

// versions.json の 1 エントリを upsert する。build 状態や image_tag は保持する。
func (q *Queries) UpsertResoniteVersion(ctx context.Context, arg UpsertResoniteVersionParams) (ResoniteVersion, error) {
	row := q.db.QueryRow(ctx, upsertResoniteVersion,
		arg.ManifestID,
		arg.Branch,
		arg.GameVersion,
		arg.ReleasedAt,
	)
	var i ResoniteVersion
	err := row.Scan(
		&i.ManifestID,
		&i.Branch,
		&i.GameVersion,
		&i.ReleasedAt,
		&i.BuildStatus,
		&i.ImageTag,
		&i.BuiltWithAppVersion,
		&i.BuiltAt,
		&i.BuildError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
