// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package db

import (
	"context"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_key) VALUES ($1, $2)
ON CONFLICT (role_id, permission_key) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID        string
	PermissionKey string
}

// seedロールへの追加は DB トリガーが阻止する。
func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionKey)
	return err
}

const getUserPermissionsForGroup = `-- name: GetUserPermissionsForGroup :many
SELECT DISTINCT rp.permission_key
FROM group_members gm
INNER JOIN role_permissions rp ON rp.role_id = gm.role_id
WHERE gm.user_id = $1::text
  AND gm.group_id = $2::text
`

type GetUserPermissionsForGroupParams struct {
	UserID  string
	GroupID string
}

// 指定 (user, group) に対する permission_key を引く。
// group に所属していない場合は空集合が返る。
func (q *Queries) GetUserPermissionsForGroup(ctx context.Context, arg GetUserPermissionsForGroupParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsForGroup, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT permission_key FROM role_permissions WHERE role_id = $1 ORDER BY permission_key
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionsForRoles = `-- name: ListRolePermissionsForRoles :many
SELECT role_id, permission_key
FROM role_permissions
WHERE role_id = ANY($1::text[])
ORDER BY role_id, permission_key
`

// 複数ロール分まとめて取得。permission インターセプタで使う想定。
func (q *Queries) ListRolePermissionsForRoles(ctx context.Context, roleIds []string) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissionsForRoles, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSystemPermissions = `-- name: ListUserSystemPermissions :many
SELECT DISTINCT rp.permission_key
FROM group_members gm
INNER JOIN role_permissions rp ON rp.role_id = gm.role_id
WHERE gm.user_id = $1::text
  AND gm.group_id = 'system'
`

// 指定ユーザーが system グループ経由で保持する permission_key 一覧。
// (system:* の判定や、system:group.manage による personal/normal の代行権限判定に使う)
func (q *Queries) ListUserSystemPermissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserSystemPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_key = $2
`

type RemoveRolePermissionParams struct {
	RoleID        string
	PermissionKey string
}

// seedロールからの削除は DB トリガーが阻止する。
func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.Exec(ctx, removeRolePermission, arg.RoleID, arg.PermissionKey)
	return err
}
