// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file hdlctrl/v1/user.proto (package hdlctrl.v1, syntax proto3)
 

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hdlctrl/v1/user.proto.
 */
export const file_hdlctrl_v1_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChVoZGxjdHJsL3YxL3VzZXIucHJvdG8SCmhkbGN0cmwudjEiKgoXR2V0VG9rZW5CeUFQSUtleVJlcXVlc3QSDwoHYXBpX2tleRgBIAEoCSIpChhHZXRUb2tlbkJ5QVBJS2V5UmVzcG9uc2USDQoFdG9rZW4YASABKAkiOQoZR2V0VG9rZW5CeVBhc3N3b3JkUmVxdWVzdBIKCgJpZBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIrChpHZXRUb2tlbkJ5UGFzc3dvcmRSZXNwb25zZRINCgV0b2tlbhgBIAEoCTLVAQoLVXNlclNlcnZpY2USXwoQR2V0VG9rZW5CeUFQSUtleRIjLmhkbGN0cmwudjEuR2V0VG9rZW5CeUFQSUtleVJlcXVlc3QaJC5oZGxjdHJsLnYxLkdldFRva2VuQnlBUElLZXlSZXNwb25zZSIAEmUKEkdldFRva2VuQnlQYXNzd29yZBIlLmhkbGN0cmwudjEuR2V0VG9rZW5CeVBhc3N3b3JkUmVxdWVzdBomLmhkbGN0cmwudjEuR2V0VG9rZW5CeVBhc3N3b3JkUmVzcG9uc2UiAEK3AQoOY29tLmhkbGN0cmwudjFCCVVzZXJQcm90b1ABWlFnaXRodWIuY29tL2hhbnRhYmFydTEwMTQvYmFydS1yZXNvLWhlYWRsZXNzLWNvbnRyb2xsZXIvcGJnZW4vaGRsY3RybC92MTtoZGxjdHJsdjGiAgNIWFiqAgpIZGxjdHJsLlYxygIKSGRsY3RybFxWMeICFkhkbGN0cmxcVjFcR1BCTWV0YWRhdGHqAgtIZGxjdHJsOjpWMWIGcHJvdG8z",
  );

/**
 * @generated from message hdlctrl.v1.GetTokenByAPIKeyRequest
 */
export type GetTokenByAPIKeyRequest =
  Message<"hdlctrl.v1.GetTokenByAPIKeyRequest"> & {
    /**
     * @generated from field: string api_key = 1;
     */
    apiKey: string;
  };

/**
 * Describes the message hdlctrl.v1.GetTokenByAPIKeyRequest.
 * Use `create(GetTokenByAPIKeyRequestSchema)` to create a new message.
 */
export const GetTokenByAPIKeyRequestSchema: GenMessage<GetTokenByAPIKeyRequest> =
  /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 0);

/**
 * @generated from message hdlctrl.v1.GetTokenByAPIKeyResponse
 */
export type GetTokenByAPIKeyResponse =
  Message<"hdlctrl.v1.GetTokenByAPIKeyResponse"> & {
    /**
     * @generated from field: string token = 1;
     */
    token: string;
  };

/**
 * Describes the message hdlctrl.v1.GetTokenByAPIKeyResponse.
 * Use `create(GetTokenByAPIKeyResponseSchema)` to create a new message.
 */
export const GetTokenByAPIKeyResponseSchema: GenMessage<GetTokenByAPIKeyResponse> =
  /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 1);

/**
 * @generated from message hdlctrl.v1.GetTokenByPasswordRequest
 */
export type GetTokenByPasswordRequest =
  Message<"hdlctrl.v1.GetTokenByPasswordRequest"> & {
    /**
     * @generated from field: string id = 1;
     */
    id: string;

    /**
     * @generated from field: string password = 2;
     */
    password: string;
  };

/**
 * Describes the message hdlctrl.v1.GetTokenByPasswordRequest.
 * Use `create(GetTokenByPasswordRequestSchema)` to create a new message.
 */
export const GetTokenByPasswordRequestSchema: GenMessage<GetTokenByPasswordRequest> =
  /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 2);

/**
 * @generated from message hdlctrl.v1.GetTokenByPasswordResponse
 */
export type GetTokenByPasswordResponse =
  Message<"hdlctrl.v1.GetTokenByPasswordResponse"> & {
    /**
     * @generated from field: string token = 1;
     */
    token: string;
  };

/**
 * Describes the message hdlctrl.v1.GetTokenByPasswordResponse.
 * Use `create(GetTokenByPasswordResponseSchema)` to create a new message.
 */
export const GetTokenByPasswordResponseSchema: GenMessage<GetTokenByPasswordResponse> =
  /*@__PURE__*/
  messageDesc(file_hdlctrl_v1_user, 3);

/**
 * @generated from service hdlctrl.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc hdlctrl.v1.UserService.GetTokenByAPIKey
   */
  getTokenByAPIKey: {
    methodKind: "unary";
    input: typeof GetTokenByAPIKeyRequestSchema;
    output: typeof GetTokenByAPIKeyResponseSchema;
  };
  /**
   * @generated from rpc hdlctrl.v1.UserService.GetTokenByPassword
   */
  getTokenByPassword: {
    methodKind: "unary";
    input: typeof GetTokenByPasswordRequestSchema;
    output: typeof GetTokenByPasswordResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_hdlctrl_v1_user, 0);
